name: cd

on:
  push:
    tags:
      - v*

  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
          project_id: ${{ vars.PROJECT_ID }}
          token_format: 'access_token'
      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ vars.GCP_CLOUDRUN_SERVICE_NAME }}
          region: ${{ secrets.GCP_CLOUDRUN_SERVICE_REGION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          env_vars: |
            APP_ID=${{ secrets.APP_ID }}
            PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}
          flags: --allow-unauthenticated
          source: .
