name: cd

on:
#  push:
#    tags:
#      - v*

  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    environment: 
      name: production
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v3
      - name: 'Authenticate with GCP'
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}
      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ secrets.GCP_CLOUDRUN_SERVICE_NAME }}
          region: ${{ secrets.GCP_CLOUDRUN_SERVICE_REGION }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          env_vars: |
            APP_ID=${{ secrets.APP_ID }}
            PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}
          flags: --allow-unauthenticated
          source: .
#      - name: "Test OIDC"
#        run: |
#          gcloud artifacts repositories create test --location=us-central1 --repository-format=docker
#          gcloud artifacts repositories describe test --location=us-central1
